//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility.RegularExpression {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegularExpressionString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegularExpressionString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.RegularExpression.RegularExpressionString", typeof(RegularExpressionString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1[3458]\d{9}$.
        /// </summary>
        internal static string AllMobile {
            get {
                return ResourceManager.GetString("AllMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((^((1[8-9]\d{2})|([2-9]\d{3}))([-\/\._])(10|12|0?[13578])([-\/\._])(3[01]|[12][0-9]|0?[1-9])$)|(^((1[8-9]\d{2})|([2-9]\d{3}))([-\/\._])(11|0?[469])([-\/\._])(30|[12][0-9]|0?[1-9])$)|(^((1[8-9]\d{2})|([2-9]\d{3}))([-\/\._])(0?2)([-\/\._])(2[0-8]|1[0-9]|0?[1-9])$)|(^([2468][048]00)([-\/\._])(0?2)([-\/\._])(29)$)|(^([3579][26]00)([-\/\._])(0?2)([-\/\._])(29)$)|(^([1][89][0][48])([-\/\._])(0?2)([-\/\._])(29)$)|(^([2-9][0-9][0][48])([-\/\._])(0?2)([-\/\._])(29)$)|(^([1][89][2468][048])([-\/\._])(0?2)([-\/\._])( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9a-zA-Z]*$.
        /// </summary>
        internal static string ECDomain {
            get {
                return ResourceManager.GetString("ECDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((\d{1,2}?)|100)$.
        /// </summary>
        internal static string Int100 {
            get {
                return ResourceManager.GetString("Int100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9]\d*$.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [\w|\W]{1,1024}.
        /// </summary>
        internal static string Max1024 {
            get {
                return ResourceManager.GetString("Max1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [\w|\W]{1,30}.
        /// </summary>
        internal static string Max30 {
            get {
                return ResourceManager.GetString("Max30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [\w|\W]{1,512}.
        /// </summary>
        internal static string Max512 {
            get {
                return ResourceManager.GetString("Max512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1(3[4-9]|4[7]|5[012789]|8[278])\d{8}$.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d+(\.\d\d)?$.
        /// </summary>
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[^\u4e00-\u9fa5]+$.
        /// </summary>
        internal static string NoChinese {
            get {
                return ResourceManager.GetString("NoChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((\d{11})|^((\d{7,8})|(\d{10,12})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1}))$).
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?!^[0-9]*$)(?!^[a-zA-Z]*$)^([a-zA-Z0-9]{8,16})$.
        /// </summary>
        internal static string Pwd {
            get {
                return ResourceManager.GetString("Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .*.
        /// </summary>
        internal static string PwdBak {
            get {
                return ResourceManager.GetString("PwdBak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码长度为8-16位，至少包含一个数字和字母，不包含特殊字符。.
        /// </summary>
        internal static string PwdErrorMessage {
            get {
                return ResourceManager.GetString("PwdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9]{6,18}$.
        /// </summary>
        internal static string SICode {
            get {
                return ResourceManager.GetString("SICode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(http|https|ftp)\://(([a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3})|((\d+)\.(\d+)\.(\d+)\.(\d+)))(:[a-zA-Z0-9]*)?/?([a-zA-Z0-9\-\._\?\,\’/\\\+&amp;%\$#\=~])*$.
        /// </summary>
        internal static string SIURL {
            get {
                return ResourceManager.GetString("SIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\(\d{3,4}\)|\d{3,4}-|\s)?\d{7,8}$.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(http|https|ftp)\://[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(:[a-zA-Z0-9]*)?/?([a-zA-Z0-9\-\._\?\,\’/\\\+&amp;%\$#\=~])*$.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
    }
}
